### ISSUE TITLE
请问一下api模块里的jwt问题

### ISSUE THREAD

**Issue by WuJiY** [yupoxiong/BearAdmin#1]
如果jwt过期了怎么保持登录状态？还有就是如何退出？

**Comment by yupoxiong** [comment]
比如token设置了一个小时过期，可以给token加一个刷新时间，比如12小时，如果在过期12小时内，客户端可以用这个过期的token换取新的token，这样来保持登录状态，退出的话，可以配合服务端设置token黑名单来使用。
